pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:dkostka/aenmd_cli.git
          - cd aenmd_cli.git
          - git push --mirror git@github.com:kostkalab/aenmd_cli.git
